# Generated by Django 6.0 on 2025-12-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ties',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '2'), (2, '4/6')], null=True),
        ),
    ]
