# Generated by Django 6.0 on 2026-02-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_reverse',
            field=models.BooleanField(default=False),
        ),
    ]
