# Generated by Django 6.0 on 2025-12-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products_ties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ties',
            field=models.PositiveSmallIntegerField(choices=[(1, '2'), (2, '4/6')]),
        ),
    ]
